# Site settings
title: Michael Gray's Blog and Projects
description: A place to catalog my transition into the Data Science field
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://graymichaelj.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Gray, PhD
user_description: I spent almost a decade conducting human neuroscience research involving EEG, eye-tracking, and behavioral measures. Now, I have decided to leave academia behind and transition into the Data Science industry. This journey begins with me starting a MS program in Data Science and Business Analytics this Fall.
user_title: Cognitive Neuroscientist and Aspiring Data Scientist
email: graymichaelj@outlook.com
#twitter_username: 
github_username:  graymichaelj
#gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
